services:
  web:
    image: python:3.9-slim
    container_name: flask_app
    command: bash -c "pip install -r requirements.txt && python app.py"
    volumes:
      - .:/app
      - ./requirements.txt:/app/requirements.txt
      - ./app.py:/app/app.py
    working_dir: /app
    ports:
      - "5000:5000"
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_files:/var/www/html

#  git:
#    image: alpine:latest
#    container_name: git
#    command: sh -c "while true; do sleep 30; git pull; done"
#    volumes:
#      - .:/app
#    working_dir: /app

volumes:
  static_files:
