services:
  web:
    image: python:3.11-slim
    container_name: flask_app
    command: bash -c "apt-get update && apt-get install -y libfbclient2 && pip install -r requirements.txt && python main.py"
    volumes:
      - .:/app
      - ./static:/app/static
      - ./templates:/app
      - ./requirements.txt:/app/requirements.txt
      - ./main.py:/app/main.py
      - firebird_client:/app/firebird
    working_dir: /app
    environment:
      - FIREBIRD_HOME=/app/firebird
    ports:
      - "5000:5000"
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    container_name: nginx
    command: bash -c "chmod 777 /app/static/. && nginx -g 'daemon off;'"
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - .:/app

  firebird:
    image: firebirdsql/firebird
    restart: always
    environment:
      - FIREBIRD_ROOT_PASSWORD=masterkey
      - FIREBIRD_USER=SYSDBA
      - FIREBIRD_PASSWORD=masterkey
      - FIREBIRD_DATABASE=mirror.fdb
      - FIREBIRD_DATABASE_DEFAULT_CHARSET=UTF8
    volumes:
      - ./data:/var/lib/firebird/data


#  git:
#    image: alpine:latest
#    container_name: git
#    command: sh -c "while true; do sleep 30; git pull; done"
#    volumes:
#      - .:/app
#    working_dir: /app

volumes:
  static_files:
  firebird_client:
